<!DOCTYPE html>
<html lang="fr">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

  <title>Ajouter une tache</title>
</head>

<body>
  <?php include './templates/_partials/navbar.phtml'; ?>
  <div class="container">
    <form action="../todo/task.php" method="POST">
      <fieldset>
        <legend>Ajouter une tache</legend>
        <div>
          <label for="nameTask" class="form-label mt-4">Nom de la tache</label>
          <input type="text" class="form-control" id="nameTask" name="nameTask" placeholder="Enter your task">
        </div>
        <div>
          <label for="descriptionTask" class="form-label mt-4">Description</label>
          <textarea class="form-control" id="descriptionTask" name="descriptionTask" rows="3" placeholder="Describe your task"></textarea>
        </div>
        <div>
          <label for="dateTask" class="form-label mt-4">Echéance de la tache</label>
          <input type="date" class="form-control" id="dateTask" name="dateTask" placeholder="date of end your task">
        </div>
        <div>
          <div>
            <label for="serviceTask" class="form-label mt-4">Nom du service</label>
            <input type="text" class="form-control" id="serviceTask" name="serviceTask" placeholder="Enter name of service">
          </div>
          <div>
            <label for="destinataireTask" class="form-label mt-4">Destinataire</label>
            <input type="text" class="form-control" id="destinataireTask" name="destinataireTask" placeholder="quality of technical">
          </div>
          <fieldset>
            <legend class="mt-4">Identité de l'utilisateur</legend>
            <div>
              <label for="roleUser" class="form-label mt-4">Role</label>
              <select class="form-select" name="roleUser" id="roleUser">
                <option value="directeur">directeur</option>
                <option value="technicien">technicien</option>
                <option value="client">client</option>
              </select>
            </div>
            <div>
              <label for="emailUser" class="form-label mt-4">Email</label>
              <input type="email" class="form-control" id="emailUser" name="emailUser" placeholder="your email">
            </div>
            <div>
              <label for="mdpUser" class="form-label mt-4">Mot de passe</label>
              <input type="password" class="form-control" id="mdpUser" name="mdpUser" placeholder="your password">
            </div>
            <div class="mt-4">
              <label for="boolUser" class="form-label mt-4">Actif</label>
              <select class="form-select" name="boolUser" id="boolUser">
                <option value="Oui">Oui</option>
                <option value="Non">Non</option>
              </select>
            </div>
          </fieldset>
          <button type="submit" class="btn btn-sm btn-primary rounded-pill float-end" >Valider</button>
      </fieldset>
    </form>
  </div>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>

</html>