<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create User</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
</head>
<body>
    <header>
      <div class="text-center"><h1>Create User</h1></div>
    </header>
    <main>
    <div class="container">
    <form class="d-flex flex-column align-items-center text-center" method="POST">
  <div class="mb-3">
    <label for="role" class="form-label" name="role">Role</label>
    <input type="text" class="form-control" name="role" required>
  </div>
  <div class="mb-3">
    <label for="first_name" class="form-label" name="first_name">Prénom</label>
    <input type="text" class="form-control" name="first_name" required>
  </div>
  <div class="mb-3">
    <label for="last_name" class="form-label" name="last_name">Nom</label>
    <input type="text" class="form-control" name="last_name" required>
  </div>
  <div class="mb-3">
  <input type="checkbox" class="btn-check" id="active" autocomplete="off" name="active">
  <label class="btn btn-outline-primary" for="active">Actif</label>
  </div>
  <div class="mb-3">
    <label for="identifier" class="form-label" name="identifier">Identifiant</label>
    <input type="text" class="form-control" name="identifier" required>
  </div>
  <div class="mb-3">
    <label for="password" class="form-label" name="password">Password</label>
    <input type="password" class="form-control" name="password" required>
  </div>
  <div class="mb-3 form-check">
  </div>
  <button type="submit" class="btn btn-primary w-30" name="create_user">Create</button>
</form>
<?php include 'read_users.phtml' ?>
    </div>
    </main>
    <footer>

    </footer>
    
</body>
</html>






