<html lang="en">
<head>
  
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>form_task</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
  <title>FormTask</title>

</head>

<body>
    <header>

    </header>
<main>
    <section>
       
 <div class="container d-flex flex-column align-items-center text-center" action="#" method="post ">
  <div class="row align-items-start">
    <div class="col-12">   

<h3>Ajouter une tâche</h3>
        <form action="" method="post">



    <div class="mb-3">
  <label for="name" class="form-label form-control-lg form-control-sm">Name</label>
  <input type="text" class="name" id="name"  required>
</div>
<div class="mb-3">
  <label for="description" class="form-label align-self-center"  >Description</label>
  <textarea class="description" id="description" ></textarea>
</div>

<div class="mb-3">
  <label for="author" class="form-label">Author</label>
  <input type="text" class="author" id="author"  required>
</div>
<div class="mb-3">
  <label for="status" class="form-label<">Status</label>
  <input type="text" class="author" id="status" required>
</div>

<div class="mb-3">
  <label for="Date_due" class="form-label">Date_due</label>
  <input type="date" class="Date_due" id="Date_due" required>
</div>
<button type="button" class="form-label">Ajouter</button>

   </form> </div></div></div>
    </section>
</main>
</body>
</html>