<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create User</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" 
    integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
</head>
<body>
    <header>
    
    </header>
    <main>
    <div class="container">
<div class="text-center"><h1>Create User</h1></div>
    <form class="d-flex flex-column align-items-center text-center" method="POST">
  <div class="mb-3">
    <label for="role" class="form-label" name="role">Role</label>
    <input type="text" class="form-control" name="role" required>
  </div>
  <div class="mb-3">
    <label for="first_name" class="form-label" name="first_name">Prénom</label>
    <input type="text" class="form-control" name="first_name" required>
  </div>
  <div class="mb-3">
    <label for="last_name" class="form-label" name="last_name">Nom</label>
    <input type="text" class="form-control" name="last_name" required>
  </div>
  <div class="mb-3">
  <input type="checkbox" class="btn-check" id="active" autocomplete="off" name="active">
  <label class="btn btn-outline-primary" for="active">Actif</label>
  </div>
  <div class="mb-3">
    <label for="identifier" class="form-label" name="identifier">Identifiant</label>
    <input type="text" class="form-control" name="identifier" required>
  </div>
  <div class="mb-3">
    <label for="password" class="form-label" name="password">Password</label>
    <input type="password" class="form-control" name="password" required>
  </div>
  <div class="mb-3 form-check">
  </div>
  <button type="submit" class="btn btn-primary w-30" name="create_user">Create</button>
</form>
<h2>Users</h2>
<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">First</th>
      <th scope="col">Last</th>
      <th scope="col">Handle</th>
    </tr>
  </thead>
  
  <tbody>
    <tr>
      <th scope="row">1</th>
      <td>Mark</td>
      <td>Otto</td>
      <td>@mdo</td>
    </tr>
    <tr>
      <th scope="row">2</th>
      <td>Jacob</td>
      <td>Thornton</td>
      <td>@fat</td>
    </tr>
    <tr>
      <th scope="row">3</th>
      <td colspan="2">Larry the Bird</td>
      <td>@twitter</td>
    </tr>
  </tbody>
</table>
    </div>
    </main>
    <footer>

    </footer>
    
</body>
</html>






