<html lang="en">
<head>
  
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Classic Models - Accueil</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
  <title>FormTask</title>

</head>

<body>
    <header>

    </header>
<main>
    <section>
       
 <div class="container text-center">
  <div class="row align-items-start">
    <div class="col-12">   

        <form action="" method="post">


<h1>CreateTask</h1>
        <div class="mb-2">
  <label for="name" class="name">Name</label>
  <input type="text" class="name" id="name" placeholder="name" required>
</div>
<div class="mb-3">
  <label for="description" class="form-label">Description</label>
  <textarea class="description" id="description" rows="2"></textarea>
</div>

<div class="mb-3">
  <label for="author" class="author">Author</label>
  <input type="author" class="author" id="name" placeholder="author" required>
</div>
<div class="mb-3">
  <label for="status" class="status<">Status</label>
  <input type="status" class="author" id="status" placeholder="status" required>
</div>

<div class="mb-3">
  <label for="Date_due" class="Date_due">Date_due</label>
  <input type="Date_due" class="Date_due" id="Date_due" placeholder="status" required>
</div>
<button type="button" class="addtask">Ajouter</button>

   </form>     </div></div></div>
    </section>
</main>
</body>
</html>