<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Read Users</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" 
    integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">

</head>
<body>
    <h2>Users</h2>
<table class="table">
  <thead>
    <tr class="table-light">
      <th scope="col">PRENOM</th>
      <th scope="col">NOM</th>
      <th scope="col">ROLE</th>
    </tr>
  </thead>
  <tbody>
    <?php  foreach($getUsers as $user): ?>
    <tr class="table-success">
      <td><?php echo htmlspecialchars($user['first_name'], ENT_QUOTES, 'UTF-8')?></td>
      <td><?php echo htmlspecialchars($user['last_name'], ENT_QUOTES, 'UTF-8')?></td>
      <td><?php echo html_entity_decode(htmlspecialchars($user['role'], ENT_QUOTES, 'UTF-8'))?></td> 
      <!-- entity_decode sert à convertir les caractères spéciaux comme ' qui donne &#039; par exemple -->
    </tr>
  <?php endforeach; ?>
  </tbody>
</table>
</body>
</html>


