<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Update User</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" 
    integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">

</head>
<body>
 <header>
<div class="container">
   <div class="text-center mt-4"><h1>Update User</h1></div> 
</div>
 </header>

 <main>
    <table class="table">
  <thead>
    <tr class="table-light">
      <th scope="col">PRENOM</th>
      <th scope="col">NOM</th>
      <th scope="col">ROLE</th>
    </tr>
  </thead>
  <tbody>
    <tr class="table-success">
    <form action="../controller/update.php" method="post" name="update_user">
          <input type="hidden" name="id" id="" value="<?php echo $getUser['id'] ?>">
      <td><input type="text" name="first_name" id="" value="<?php echo $getUser['first_name'] ?>"></td>
      <td><input type="text" name="last_name" id="" value="<?php echo $getUser['last_name'] ?>"></td>
      <td><input type="text" name="role" id="" value="<?php echo $getUser['role'] ?>"></td> 
      <td><button type="submit" class="btn btn-warning w-30" name="update_user">Update</button></td> 
      </form>
    </tr>
  </tbody>
</table>
<div class="mt-4 d-flex justify-content-center">
        <a href="../controller/create.php" class="btn btn-primary w-30" name="update_user">Retour</a>
        </div> 

 </main>

 <footer>

 </footer>
    
</body>
</html>